SELECT *
FROM TEMPDB..[METRICS - APPSTORE];

--CAU 1: TOP 3 NGAY IMPRESSION CAO NHAT
SELECT TOP 3 IMPRESSION, DATE
FROM TEMPDB..[METRICS - APPSTORE]
ORDER BY IMPRESSION DESC;

--CAU 2: GIÁ TRỊ TOP 1 IMPRESSION
SELECT MAX(IMPRESSION) AS TOP_1_IMP_PER_DAY
FROM TEMPDB..[METRICS - APPSTORE];

--CAU 3: TĂNG NET CỦA CHỈ SỐ IMPRESSION PER DAY
WITH IMP_CHANGES AS ( 
					SELECT DATE,CAST(IMPRESSION AS INT) AS IMPRESSION, 
					LAG(IMPRESSION) OVER(ORDER BY DATE) AS PRE_IMP
					FROM TEMPDB..[METRICS - APPSTORE]
					)

SELECT DATE,IMPRESSION - PRE_IMP AS NET_INCREASE
FROM IMP_CHANGES;

--CAU 4: THANG NÀO, NGAY NAO CÓ CHỈ TIÊU TỐT NHẤT?

--4.1.NGÀY.THÁNG.NĂM CÓ SỐ IMP CAO NHẤT
SELECT DATE
FROM TEMPDB..[METRICS - APPSTORE]
WHERE IMPRESSION = (SELECT MAX(IMPRESSION) 
					FROM TEMPDB..[METRICS - APPSTORE])

--4.2.NGÀY TRONG CÁC THÁNG CÓ IMP CAO NHẤT

SELECT	DAY(DATE) AS DAY, 
		SUM(CAST(IMPRESSION AS INT)) AS DAY_OF_MONTH_IMP
FROM TEMPDB..[METRICS - APPSTORE]
GROUP BY DAY(DATE)
ORDER BY DAY_OF_MONTH_IMP DESC
OFFSET 0 ROWS FETCH FIRST 1 ROWS ONLY;

--4.3. THÁNG CÓ IMP CAO NHẤT TRONG CÁC NĂM.

SELECT	MONTH(DATE) AS MONTH, 
		SUM(CAST(IMPRESSION AS INT)) AS MONTH_OF_YEAR_IMP
FROM TEMPDB..[METRICS - APPSTORE]
GROUP BY MONTH(DATE)
ORDER BY MONTH_OF_YEAR_IMP DESC
OFFSET 0 ROWS FETCH FIRST 1 ROWS ONLY;

--4.4. THÁNG/NĂM CÓ IMP CAO NHẤT

SELECT	CONCAT(MONTH(DATE),'/',YEAR(DATE)) AS M_Y,
		SUM(CAST(IMPRESSION AS INT)) AS TOP_IMPRESSION
FROM TEMPDB..[METRICS - APPSTORE]
GROUP BY CONCAT(MONTH(DATE),'/',YEAR(DATE))
ORDER BY TOP_IMPRESSION DESC
OFFSET 0 ROWS FETCH FIRST 1 ROWS ONLY